theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dark"
locale                   : "en-US"
title                    : "what's the worst that could happen"
title_separator          : "-"
subtitle                 : experiments in diy infrastructure
name                     : "franny gaede"
url                      : https://librarifran.com
repository               : "mfgaede/librarifran-theme"
teaser                   : #path of fallback teaser
logo                     : #path of logo for masthead
masthead_title           : "what's the worst that could happen"
breadcrumbs              :  false
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false
search                   : true
search_full_content      : true
search_provider          : lunr
lunr:
  search_within_pages    : true
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
# Social Sharing
twitter:
  username               : mfgaede
facebook:
  username               : mfgaede
  app_id                 :
  publisher              :
social:
  type                   : Person
# Analytics
analytics:
  provider               : false
  google:
    tracking_id          :
    anonymize_ip         : false # true, false (default)
author:
  name             : "franny gaede"
  avatar           : /assets/img/profile2023.JPG
  bio              : "she / her. librarian, technologist, gardener, calligrapher."
  location         : "eugene, or"
  links:
    - label: "work"
      icon: "fas fa-fw fa-briefcase"
      url: "/categories/#work"
    - label: "photos"
      icon: "fas fa-fw fa-camera-retro"
      url: "/categories/#photos"
    - label: "links"
      icon: "fas fa-fw fa-link"
      url: "/categories/#links"
    - label: "music"
      icon: "fas fa-fw fa-music"
      url: "/categories/#music"
    - label: "videos"
      icon: "fas fa-fw fa-video"
      url: "/categories/#videos"
    - label: "art"
      icon: "fas fa-fw fa-paint-brush"
      url: "/categories/#art"

footer:
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mfgaede@gmail.com"
    - label: "website"
      icon: "fas fa-fw fa-link"
      url: "https://mfgaede.com"
    - label: "mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://hcommons.social/@librarifran"
    - label: "facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/mfgaede"
    - label: "github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mfgaede"
# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
# Outputting
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: 'en_US' 
  trail: 
    before: 2
    after: 2
  extension: html
  indexpage: 'index'
  permalink: /page/:num.html
timezone: America/Los_Angeles
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-liquify
#Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      breadcrumbs: true
      share: true
      related: true
    sidebar:
      nav: "categoryposts"