# Theme Configuration
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "contrast"

# Site Settings
locale: "en-US"
title: "Franny Gaede"
title_separator: "-"
subtitle: 
name: ""
url: "https://librarifran.com"
repository: "mfgaede/librarifran-theme"
teaser: # path of fallback teaser image
logo: # path of logo for masthead
masthead_title: ""
breadcrumbs: false

# Feed Settings
atom_feed:
  path: # blank (default) uses feed.xml
  hide: false

# Search Settings
search: true
search_full_content: true
search_provider: lunr
lunr:
  search_within_pages: true

# SEO Settings
google:
  search_engine_id: # YOUR_SEARCH_ENGINE_ID
  instant_search: # false (default), true
google_site_verification:
bing_site_verification:

# Social Settings
social:
  type: Person

# Analytics Settings
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip: false

# Author Settings
author:
  name: "Franny Gaede"
  avatar: "/assets/img/profile2024.jpg"
  bio: "she / her / hers"
  location: "eugene, or"
  links:
    - label: "Posts"
      icon: "fa-solid fa-newspaper"
      url: "/categories/posts"
    - label: "Work"
      icon: "fa-solid fa-briefcase"
      url: "/categories/work"
    - label: "Photos"
      icon: "fa-solid fa-camera"
      url: "/categories/photos"
    - label: "Links"
      icon: "fa-solid fa-link"
      url: "/categories/links"
    - label: "Music"
      icon: "fa-solid fa-music"
      url: "/categories/music"
    - label: "Videos"
      icon: "fa-solid fa-video"
      url: "/categories/videos"
    - label: "Art"
      icon: "fa-solid fa-palette"
      url: "/categories/art"

# Footer Settings
footer:
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:mfgaede@gmail.com"
    - label: "Bluesky"
      icon: "custom-bluesky"
      url: "https://bsky.app/profile/librarifran.com"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://hcommons.social/@librarifran"
    - label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/mfgaede"

# File Settings
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - assets/node_modules
  - Capfile
  - CHANGELOG
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp

# Build Settings
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    wrap: true
    default_lang: html
    css_class: 'highlight'
    block:
      line_numbers: false

# Sass Processing
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true

# Pagination Settings
pagination:
  enabled: true
  paginate_path: '/page:num/'
  collection: 'posts'
  per_page: 15
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Time Settings
timezone: America/Los_Angeles

# Plugin Settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-liquify
  - jekyll-pdf-embed
  - jekyll-linkpreview
  - jekyll-archives

font_awesome:
  kit_url: "https://kit.fontawesome.com/6765f5a2a7.js"

# Archive Settings
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts: 
    year: year
    category: category
    tag: tag
  permalinks:
    year: '/posts/:year/'
    tag: '/tags/:name/'
    category: '/categories/:name/'

# Default Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      comments: false

# Comment Settings
comments:
  provider: "custom"